
module.exports = {
  // experimental: {
  //   darkModeVariant: true
  // },
  mode:"jit",
  darkMode: 'class',
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./pages/**/**/*.{js,ts,jsx,tsx}",
    "./pages/**/**/**/*.{js,ts,jsx,tsx}",
    "./pages/**/**/**/**/*.{js,ts,jsx,tsx}",
    "./pages/**/**/**/**/**/*.{js,ts,jsx,tsx}",
    "./pages/**/**/**/**/**/**/*.{js,ts,jsx,tsx}",
    "./pages/**/**/**/**/**/**/**/*.{js,ts,jsx,tsx}",
    "./pages/**/**/**/**/**/**/**/**/*.{js,ts,jsx,tsx}",
    "./pages/**/**/**/**/**/**/**/**/**/*.{js,ts,jsx,tsx}",
    "./pages/**/**/**/**/**/**/**/**/**/**/*.{js,ts,jsx,tsx}",
    "./src/utils/**/*.{js,ts,jsx,tsx}",
    "./src/utils/**/**/*.{js,ts,jsx,tsx}",
    "./src/utils/**/**/**/*.{js,ts,jsx,tsx}",
    "./src/utils/**/**/**/**/*.{js,ts,jsx,tsx}",
    "./src/component/**/*.{js,ts,jsx,tsx}",
    "./src/component/**/**/*.{js,ts,jsx,tsx}",
    "./src/component/**/**/**/*.{js,ts,jsx,tsx}",
    "./src/component/**/**/**/**/*.{js,ts,jsx,tsx}",
    "./src/component/**/**/**/**/**/*.{js,ts,jsx,tsx}",
    "./src/component/**/**/**/**/**/**/*.{js,ts,jsx,tsx}",
    "./src/component/**/**/**/**/**/**/**/*.{js,ts,jsx,tsx}",
    "./src/component/**/**/**/**/**/**/**/**/*.{js,ts,jsx,tsx}",
    "./src/component/**/**/**/**/**/**/**/**/**/*.{js,ts,jsx,tsx}",
    "./src/component/**/**/**/**/**/**/**/**/**/**/*.{js,ts,jsx,tsx}",
    "./src/component/**/**/**/**/**/**/**/**/**/**/**/*.{js,ts,jsx,tsx}",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./src/**/**/*.{js,ts,jsx,tsx}",
    "./src/**/**/**/*.{js,ts,jsx,tsx}",
    "./src/**/**/**/**/*.{js,ts,jsx,tsx}",
    "./src/**/**/**/**/**/*.{js,ts,jsx,tsx}",
    "./src/**/**/**/**/**/**/*.{js,ts,jsx,tsx}",
    "./src/**/**/**/**/**/**/**/*.{js,ts,jsx,tsx}",
    "./src/**/**/**/**/**/**/**/**/*.{js,ts,jsx,tsx}",
    "./src/**/**/**/**/**/**/**/**/**/*.{js,ts,jsx,tsx}",
    "./src/**/**/**/**/**/**/**/**/**/**/*.{js,ts,jsx,tsx}",
    "./src/**/**/**/**/**/**/**/**/**/**/**/*.{js,ts,jsx,tsx}",
    "./src/**/**/**/**/**/**/**/**/**/**/**/**/*.{js,ts,jsx,tsx}",
    "./src/**/**/**/**/**/**/**/**/**/**/**/**/**/*.{js,ts,jsx,tsx}",
    "./src/**/**/**/**/**/**/**/**/**/**/**/**/**/**/*.{js,ts,jsx,tsx}",
    "./src/**/**/**/**/**/**/**/**/**/**/**/**/**/**/**/*.{js,ts,jsx,tsx}",
    "./src/**/**/**/**/**/**/**/**/**/**/**/**/**/**/**/**/*.{js,ts,jsx,tsx}",
    "./src/**/**/**/**/**/**/**/**/**/**/**/**/**/**/**/**/**/*.{js,ts,jsx,tsx}",
    "./src/**/**/**/**/**/**/**/**/**/**/**/**/**/**/**/**/**/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    fontFamily: {
      // 'sans': ["Roboto", 'sans-serif'],
      'sans': ["SFPro", 'sans-serif'],
      'body': ['TTNormsPro', 'sans-serif'],
    },

    extend: {},

  },
  variants: ['dark', 'dark-hover', 'dark-group-hover', 'dark-even', 'dark-odd'],
  plugins: [
    // require('tailwindcss-prefers-dark-mode')('prefers-dark'),
    // require('tailwindcss-dark-mode')(),
    // require('tailwindcss-interaction-variants'),
    require('@tailwindcss/forms'),
    require('@tailwindcss/line-clamp'),
  ],
}
