import React from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { query, initThinBackend, ensureIsUser, getCurrentUser } from 'thin-backend';
import { useQuery, useCurrentUser } from 'thin-backend/react';
import { useEffect, useState } from 'react';
import Headers from '../src/component/headers/index'

initThinBackend({ host: process.env.NEXT_PUBLIC_BACKEND_URL });

const Home: NextPage = () => {

  // useEffect(() => {
  //     ensureIsUser(); // Trigger login
  // }, []);

  // @ts-ignore
    return (
    <React.Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className={'w-full py-10'}>
            <div className="w-full max-w-6xl mx-auto flex flex-col space-y-10">
                <div className="">
                    <h1 className={'text-3xl text-white text-roboto'}>Hallooo</h1>
                </div>
                <div className="w-full bg-slate-700 min-h-[420px] rounded-xl shadow-xl">

                </div>
            </div>
        </div>
    </React.Fragment>
  )
}

export default Home
