import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { query, initThinBackend, ensureIsUser, getCurrentUser } from 'thin-backend';
import { useQuery, useCurrentUser } from 'thin-backend/react';
import { useEffect, useState } from 'react';

initThinBackend({ host: process.env.NEXT_PUBLIC_BACKEND_URL });

const Home: NextPage = () => {

  useEffect(() => {
      ensureIsUser(); // Trigger login
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={'w-full border border-red-500'}>
        testing
      </div>

    </div>
  )
}

export default Home
